# FROM jenkins/inbound-agent:latest
# USER root

# RUN apt-get update && apt-get install -y lsb-release && \
#    curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
#    https://download.docker.com/linux/debian/gpg && \
#    echo "deb [arch=$(dpkg --print-architecture) \
#    signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
#    https://download.docker.com/linux/debian \
#    $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && \
#    apt-get update && apt-get install -y docker.io && \
#    apt-get clean && rm -rf /var/lib/apt/lists/*  && \
#    usermod -aG docker jenkins

# USER jenkins


# 기본 Jenkins 인바운드 에이전트 이미지 사용
FROM jenkins/inbound-agent:latest

# root 사용자로 작업
USER root

# 패키지 업데이트 및 Docker와 Docker Compose 설치
RUN apt-get update && apt-get install -y \
    lsb-release \
    curl \
    python3-pip \
    && curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
    https://download.docker.com/linux/debian/gpg \
    && echo "deb [arch=$(dpkg --print-architecture) \
    signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
    https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list \
    && apt-get update && apt-get install -y docker.io \
    && curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)/docker-compose-$(uname -s)-$(uname -m)" \
    -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && usermod -aG docker jenkins

# Jenkins 사용자로 돌아가기
USER jenkins